import platform

print(platform.platform())
print(platform.platform(True,True))
print(platform.platform(1,1))
print(platform.platform(terse=1))
print(platform.platform(aliased=1))
print(platform.platform(aliased=0))
print(platform.processor())
print(platform.architecture())
print(platform.machine())
print(platform.version())
print(platform.system())
print(platform.uname())
print(len(platform.uname()))
print(platform.system_alias(3,True,"asdf"))
print("---PYTHON OUTPUTS---")
print(platform.python_version())
print(platform.python_version_tuple())
print(platform.python_compiler())
print(platform.python_build())
print(platform.python_compiler())
print(platform.python_branch())
print(platform.python_implementation())
print("################")
print(platform.libc_ver())
print(platform.java_ver())
print(platform.mac_ver())
print(platform.win32_ver())

# sample outputs crossplatforms https://pymotw.com/3/platform/
